/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/models/hangar-scene/scene.gltf -o Scene.tsx -t 
Author: Lezalit (https://sketchfab.com/Lezalit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-hangar-4b263701219446f1ab13b37a5b98bac5
Title: SCI FI HANGAR
*/

import * as THREE from 'three'
import React, { Suspense, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001_Base_0: THREE.Mesh
    Plane_Details_Cevre_0: THREE.Mesh
    Plane_Details_Cevre_0_1: THREE.Mesh
    Plane_Details_Cevre_0_2: THREE.Mesh
  }
  materials: {
    Base: THREE.MeshStandardMaterial
    Details_Cevre: THREE.MeshStandardMaterial
  }
}

export function Scene(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/hangar-scene/scene.gltf') as GLTFResult
  return (
    <Suspense fallback={<div style={{ color: 'white', fontSize: '2rem' }}>Loading...</div>}>
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_Details_Cevre_0.geometry} material={materials.Details_Cevre} />
            <mesh geometry={nodes.Plane_Details_Cevre_0_1.geometry} material={materials.Details_Cevre} />
            <mesh geometry={nodes.Plane_Details_Cevre_0_2.geometry} material={materials.Details_Cevre} />
          </group>
          <mesh geometry={nodes.Cylinder001_Base_0.geometry} material={materials.Base} position={[0, 12.325, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </Suspense>
  )
}

useGLTF.preload('/models/hangar-scene/scene.gltf')
